### ISSUE TITLE
[AVM Question/Feedback]: webdeploy_publish_basic_authentication_enabled  set to disabled if FTP state is set  to "FTPS only" 

### ISSUE THREAD

**Issue by vaiddas** [Azure/terraform-azurerm-avm-res-web-site#71]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

https://github.com/Azure/terraform-azurerm-avm-res-web-site/blob/f046263fd9685272d6853c87d8fe133d79164792/main.function_app.tf#L28C3-L28C155

`webdeploy_publish_basic_authentication_enabled = var.site_config.ftps_state == "AllAllowed" ? var.webdeploy_publish_basic_authentication_enabled : false`

I have site_config ftps_state set to "FtpsOnly" and I have set both 
  webdeploy_publish_basic_authentication_enabled = true
  ftp_publish_basic_authentication_enabled = true

but it appears that code above sets webdeploy_publish_basic_authentication_enabled  to true only if ftps_state is set to "AllAllowed" 

In Azure portal I can set FTP state to "FTPS only" and set both Basic auth publishing credential as well as "FTP basic auth"  to "On"

How can I then do this via the module? 

I want to set 
both Basic auth publishing credential as well as "FTP basic auth"  to "On" as well as FTP state to "FTPS only" 

Thanks.

**Comment by donovm4** [comment]
Hello @vaiddas - will be taking a look into this. Just to make you aware, there may be some provider issue in which you will have to manually toggle the FTP basic auth on in the portal, even with the logical fix to code.

**Comment by donovm4** [comment]
addressed in v0.6.0 release

**Comment by vaiddas** [comment]
Hi @donovm4 - sorry to ask again but is this fixed or do I still need to toggle the basic auth in the portal? 

I tried with v.0.6.0 and I am seeing 

` + webdeploy_publish_basic_authentication_enabled = false`

and I think it's because of 

`webdeploy_publish_basic_authentication_enabled = var.site_config.ftps_state == "AllAllowed" ? var.webdeploy_publish_basic_authentication_enabled : false`

and I have set ftps_state to "FtpsOnly".

**Comment by donovm4** [comment]
@vaiddas - no worries, the goal is to work out the bugs :) 

I will double check - I believe I made the fix for the `azurerm_linux_function_app`, missed to update it for the `azurerm_windows_function_app`, `azurerm_linux_web_app`, and `azurerm_windows_web_app` after testing the fix.

> NOTE: I will double-check in my testing, but there may indeed be a provider issue from what I remember that may require you to toggle through portal still. Let me make the rest of the updates and let's see if it ends up working for you (if you are willing to provide feedback)

**Comment by vaiddas** [comment]
Hi @donovm4 - sure. I will let you know but I am using `azurerm_linux_function_app `only and still see  `webdeploy_publish_basic_authentication_enabled `set to false if I set `ftps_state `to "Ftpsonly"

**Comment by donovm4** [comment]
This is the logic that should work below. If ftps is disabled (which it is by default), set the basic auth to false, but if `"AllAllowed"` or `"FtpsOnly"`, then evaluate boolean.
```
webdeploy_publish_basic_authentication_enabled = var.site_config.ftps_state == "Disabled" ? false : var.webdeploy_publish_basic_authentication_enabled
```

This is some of the module call below in main.tf. Ensure that the value is `"FtpsOnly"` as it has to be that exactly, to be evaluated correctly.
```
...
# This is the module call
module "test" {
  source = "../../"

  # source             = "Azure/avm-res-web-site/azurerm"
  # version = "0.6.1"

  enable_telemetry = false

  name                = "${module.naming.app_service.name_unique}-linux"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  kind    = "webapp"
  os_type = azurerm_service_plan.example.os_type

  service_plan_resource_id = azurerm_service_plan.example.id

  site_config = {
    ftps_state = "FtpsOnly"
  }
}
```


This is copy & pasted from my terminal while testing, just cleaned up a bit:
```
Terraform will perform the following actions:

  # azurerm_resource_group.example will be created
  + resource "azurerm_resource_group" "example" {
      ...
    }

  # azurerm_service_plan.example will be created
  + resource "azurerm_service_plan" "example" {
      ...
    }

  # random_integer.region_index will be created
  + resource "random_integer" "region_index" {
      ...
    }

  # module.naming.random_string.first_letter will be created
  + resource "random_string" "first_letter" {
      ...
    }

  # module.naming.random_string.main will be created
  + resource "random_string" "main" {
      ...
    }

  # module.test.azurerm_application_insights.this[0] will be created
  + resource "azurerm_application_insights" "this" {
      ...
    }

  # module.test.azurerm_linux_web_app.this[0] will be created
  + resource "azurerm_linux_web_app" "this" {
      ...
      + ftp_publish_basic_authentication_enabled       = true
      ...
      + webdeploy_publish_basic_authentication_enabled = true
      ...

      + site_config {
          ...
          + ftps_state                              = "FtpsOnly"
          ...
        }
    }

Plan: 7 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + name         = (known after apply)
  + resource     = (sensitive value)
  + resource_uri = (known after apply)
```
I believe the logic works. This plan was on a linux web app, but this is the logic currently on the v0.6.0 for linux function app.

In my investigation, I discovered that I may have a policy inherited from security side that audits and prevents all App Services from using basic authentication and local authentication. **I can attempt to test on a different tenant, but would you be able to check if you have such policies active?**

**Comment by donovm4** [comment]
@vaiddas - apologies if this is confusing, but I think I have found our issue. When you set `ftps_state` to `"AllAllowed"`, you can then set the ftp basic auth to on as desired, but if you set` ftps_state` to `"FtpsOnly"` it disables FTP authentication (as it resolves in Azure). That is probably why I initially coded the conditional that way.

FTP for plain text and FTPS for secure connections

**Comment by vaiddas** [comment]
Yes, I was about to update. 
In my case I have set
```
webdeploy_publish_basic_authentication_enabled = true
ftp_publish_basic_authentication_enabled = true
```
and 
set
`ftps_state = "FtpsOnly"`

but I still see 
`  + webdeploy_publish_basic_authentication_enabled = false`

**Comment by donovm4** [comment]
@vaiddas - I have been able to test this configuration with v0.6.0 in a tenant with no policies configured:
```
terraform {
  required_version = ">= 1.3.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.7.0, < 4.0.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.5.0, < 4.0.0"
    }
  }
}

# tflint-ignore: terraform_module_provider_declaration, terraform_output_separate, terraform_variable_separate
provider "azurerm" {
  features {
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
  }
}

## Section to provide a random Azure region for the resource group
# This allows us to randomize the region for the resource group.
module "regions" {
  source  = "Azure/regions/azurerm"
  version = ">= 0.3.0"
}

# This allows us to randomize the region for the resource group.
resource "random_integer" "region_index" {
  max = length(local.azure_regions) - 1
  min = 0
}
## End of section to provide a random Azure region for the resource group

# This ensures we have unique CAF compliant names for our resources.
module "naming" {
  source  = "Azure/naming/azurerm"
  version = ">= 0.3.0"
}

# This is required for resource modules
resource "azurerm_resource_group" "example" {
  location = local.azure_regions[random_integer.region_index.result]
  name     = module.naming.resource_group.name_unique
}

# This is the module call
module "test" {

  source             = "Azure/avm-res-web-site/azurerm"
  version = "0.6.0"

  enable_telemetry = false

  name                = "${module.naming.app_service.name_unique}-linux"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  kind    = "functionapp"
  os_type = "Linux"

  site_config = {
    ftps_state = "FtpsOnly"
  }

  create_service_plan = true
  new_service_plan = {
    sku_name = "S1"
  }

  function_app_create_storage_account = true
  function_app_storage_account = {
    name                = module.naming.storage_account.name_unique
    resource_group_name = azurerm_resource_group.example.name
  }
}
```
`terraform apply` and `terraform plan` (post-deployment) return smoothly with no issues / changes, and both SCM and FTP basic authentication settings stay toggled to on.

I will push another version with the updates to the logic for all app services for basic auth toggles, as well as an example deployment for basic auth with `ftps_state` configured to `"FtpsOnly"`

**Would you be able to check to ensure there are no conflicting policies on your tenant. If there are policies that you cannot bypass, I would recommend not using FTP (plain-text) if possible, if recommended by security best practices.**

**Comment by donovm4** [comment]
Also ensure that you run a `terraform init -upgrade` for the newest version after referencing a new version

**Comment by vaiddas** [comment]
@donovm4 - I have no other policy configured. 

Btw, I am using "webapp" and not "functionapp" but looks like code is same ( although different TF files ) 

I actually hardcoded all values and tested but still see 
+ webdeploy_publish_basic_authentication_enabled = false
![Screenshot 2024-06-05 094153](https://github.com/Azure/terraform-azurerm-avm-res-web-site/assets/160188307/5fb49edc-75f6-41d2-afd8-c24fb8456f45)


```
module "test" {
  source  = "Azure/avm-res-web-site/azurerm"
  version = "0.6.0"

  enable_telemetry = false
  webdeploy_publish_basic_authentication_enabled = true

  name                = "xxxxxxx"
  resource_group_name = "xxxxxxx"
  location            = "australiaeast"

  kind    = "webapp"
  os_type = "Linux"

  service_plan_resource_id = "xxxxxxxx"

     site_config = {
      ftps_state = "FtpsOnly"
    }
 }
```

**Comment by donovm4** [comment]
Understood - as mentioned earlier, the fix was made for linux function app for 0.6.0 initial for testing, so the logic would only work for linux function apps.

I am about to publish a new version that will allow for all of the app services

**Comment by donovm4** [comment]
addressed in v0.6.1 release

**Comment by vaiddas** [comment]
@donovm4  - Thanks works now.
